import type { Move } from "@/types/game";

export const MOVES: readonly Move[] = [
  {
    id: "aggressive-wobble",
    name: "Aggressive Wobble",
    power: 9,
    accuracy: 0.95,
    type: "normal",
    message: "{attacker} wobbled with hostile intent.",
  },
  {
    id: "suspicious-slap",
    name: "Suspicious Slap",
    power: 11,
    accuracy: 0.88,
    type: "normal",
    message: "{attacker} delivered a legally questionable slap.",
  },
  {
    id: "uncomfortable-stare",
    name: "Uncomfortable Stare",
    power: 8,
    accuracy: 0.98,
    type: "normal",
    message: "{attacker} made the arena deeply uncomfortable.",
  },
  {
    id: "touch-grass",
    name: "Touch Grass",
    power: 13,
    accuracy: 0.78,
    type: "internet",
    message: "{attacker} prescribed an outdoor activity.",
  },
  {
    id: "skill-issue",
    name: "Skill Issue",
    power: 10,
    accuracy: 0.92,
    type: "internet",
    message: "{attacker} diagnosed a skill issue.",
  },
  {
    id: "blocked",
    name: "Blocked",
    power: 8,
    accuracy: 1,
    type: "internet",
    message: "{attacker} ended the conversation immediately.",
  },
  {
    id: "works-on-my-machine",
    name: "Works On My Machine",
    power: 12,
    accuracy: 0.86,
    type: "programming",
    message: "{attacker} refused to reproduce the issue.",
  },
  {
    id: "force-push",
    name: "Force Push",
    power: 14,
    accuracy: 0.72,
    type: "programming",
    message: "{attacker} rewrote history without asking.",
  },
  {
    id: "friday-deployment",
    name: "Friday Deployment",
    power: 15,
    accuracy: 0.68,
    type: "programming",
    message: "{attacker} deployed and turned off notifications.",
  },
  {
    id: "existential-crisis",
    name: "Existential Crisis",
    power: 13,
    accuracy: 0.8,
    type: "strange",
    message: "{attacker} asked why any of this was necessary.",
  },
  {
    id: "become-orb",
    name: "Become Orb",
    power: 12,
    accuracy: 0.84,
    type: "strange",
    message: "{attacker} achieved a more dangerous geometry.",
  },
  {
    id: "summon-greg",
    name: "Summon Greg",
    power: 16,
    accuracy: 0.62,
    type: "strange",
    message: "{attacker} summoned Greg. Greg understood the assignment.",
  },
] as const;

export const FLAVOR_EVENTS = [
  "A chair appeared. Neither blob knows why.",
  "The crowd demanded a rollback.",
  "Greg briefly entered the arena, then remembered an appointment.",
  "A production database disappeared. Nobody made eye contact.",
] as const;
